github: brianhuster
custom:
  - https://img.vietqr.io/image/mb-9704229209586831984-print.png?addInfo=Donate%20for%20livepreview%20nvim%20plugin&accountName=PHAM%20BINH%20AN
  - https://paypal.me/brianphambinhan
