name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-version: ['v0.10.1', 'nightly']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim_version }}
    
    - name: Install plenary.nvim
      run: |
        mkdir -p ~/.local/share/nvim/lazy
        git clone https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/lazy/plenary.nvim
    
    - name: Run tests  
      run: make test
    
    - name: Run luacheck
      if: matrix.nvim-version == 'v0.10.1'  # Only run once
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install luacheck
        make luacheck
    
    - name: Run stylua check
      if: matrix.nvim-version == 'v0.10.1'  # Only run once  
      run: |
        cargo install stylua --features lua54
        stylua --check lua plugin scripts tests